CFLAGS=-Wall -g -std=c90

all: 2 7

2: strings_ex_2.c
	gcc -o strings_ex_2 strings_ex_2.c $(CFLAGS)

7: strings_ex_2.c
	gcc -o strings_ex_7 strings_ex_7.c $(CFLAGS)

clean:
	rm strings_ex_2 strings_ex_7
